### ISSUE TITLE
Question - how best to add username/password fields to a committer

### ISSUE THREAD

**Issue by danizen** [Norconex/committer-core#12]
I am extending the contributed `com.norconex.committers.elasticsearch_rest.ElasticsearchCommitter` to support HTTP Basic Auth through httpclient4's `BasicCredentialsProvider`.   The problem is how best to model it in configuration - both the username and password are required when either is provided, but since AbstractMappedCommitter overrides loadFromXML(Reader in), and since I do not fully grok your commons-lang and what is validating the XSD, I'm not quite sure as to the best structure to proceed.

Your input would be valued.

**Comment by essiembre** [comment]
``AbstractMappedCommitter`` offers ``loadFromXml(XMLConfiguration xml)`` instead.  You can load your XML from implementing that method.  The XSD is not required at all.  If present (same name as class but with ``.xsd`` extension) it will be picked up for validation.  If not present, no validation will be performed, but your XML will still be loaded just fine.

Let's say you have a "<password>" tag in your XML, then you can add this line to load it:

```xml
setPassword(xml.getString("password", getPassword()));
```

**Comment by danizen** [comment]
Also, I can model this on what you've done in the MongoDB Data Storage, for better security.
Thanks.
