### ISSUE TITLE
Question - WARC and CDX from filesystem committer

### ISSUE THREAD

**Issue by danizen** [Norconex/committer-core#15]
Pascal,

I suspect that the file system committer is not that far off from WARC and CDX, but I'm not deeply familiar with these archiving formats.   I'm wondering whether there is an ecosystem allowing the output of the filesystem committer to be gathered into WARC file(s) and CDX file(s).

Thanks,

-Dan

**Comment by essiembre** [comment]
WARC stands for "Web" archives and my experience with it, is it stores not just the pages, but the HTTP responses and headers as well.  They are often meant to be "played back" as a website (snapshot in time).  So I am not sure how it would work to create one from filesystem crawl.  Maybe you can strap a small web server on top of your filesystem and crawl the web server?

I recommend you look at https://github.com/dhamaniasad/WARCTools

It has a bunch of tools for dealing with WARC files.  A couple of these tools are proxies you can install that will monitor HTTP traffic and grow a WARC file out of it.  Using such a proxy with the HTTP Collector could be a way to build a WARC as you crawl.  Could something like that work for you?

**Comment by danizen** [comment]
Thank you, I think a proxy will work OK, because the crawler is being polite.
