### ISSUE TITLE
Error in SQL Committer

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/committer-core#17]
I am getting the following error when the crawler starts

> ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) SQLCommitter: cvc-complex-type.2.4.a: Invalid content was found starting with element 'createMissing'. One of '{sourceReferenceField, targetReferenceField, sourceContentField, targetContentField, commitBatchSize, queueDir, queueSize, maxRetries, maxRetryWait, tableName, driverPath, properties, createTableSQL, createFieldSQL, multiValuesJoiner, passwordKey, passwordKeySource, fixFieldNames, fixFieldValues}' is expected.

This the committer configuration

> 
                                  <committer` class="com.norconex.committer.sql.SQLCommitter">
				<driverClass>com.mysql.jdbc.Driver</driverClass>
				<connectionUrl>jdbc:mysql://localhost:3306/norconex</connectionUrl>
				<username>XXX</username>
				<password>$$$$$$</password>
				<createMissing>true</createMissing>
				<tableName>crawler</tableName>
												
				<createTableSQL>CREATE TABLE ${tableName} (
				wid INT NOT NULL AUTO_INCREMENT,
				PRIMARY KEY (wid),
				${targetReferenceField} VARCHAR(3000) NOT NULL, 
				${targetContentField}   LONGTEXT, 
				title VARCHAR(1000),
				keywords VARCHAR(2000),
				description VARCHAR(2000),
				Server VARCHAR(500),
				classification VARCHAR(500),
				Date VARCHAR(100),
				Last_Modified VARCHAR(100),
				document_reference VARCHAR(3000),
				imagepath VARCHAR(5000),
			
				)</createTableSQL>	
				
				<fixFieldNames>true</fixFieldNames>
				<fixFieldValues>true</fixFieldValues>

				<commitBatchSize>5</commitBatchSize>
				<queueDir>./optional/queue/path/</queueDir>
				<queueSize>10</queueSize>
				<maxRetries>3</maxRetries>
				<maxRetryWait>5000</maxRetryWait>
			</committer>

**Comment by essiembre** [comment]
It is telling you it does not know about ``<createMissing>true</createMissing>``.  That flag no longer exists with version 2.0.0 of the SQL Committer so you can simply remove it. Supplying an SQL for ``createTableSQL`` effectively creates the table if missing.

The full list of configuration options for version 2 can be found [here](https://www.norconex.com/collectors/committer-sql/configuration).

**Comment by HappyCustomers** [comment]
Thank You :)
