### ISSUE TITLE
How to remove navigation menus from HTTP source

### ISSUE THREAD

**Issue by butchersoft1** [Norconex/committer-core#21]
Hello,

I have added a document pre-parser to remove any content that appears between 

<nav class=* >menus</nav> but cannot get the function to work as a regex.   

If I add "Skip" "content" then it will "Skip this menu between the content" fine.

            
            <importer>
        
                
                <preParseHandlers> 

                     
                    <transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer" inclusive="true" caseSensitive="false">
                        <stripBetween>
                            <start><![CDATA[<nav.*>]]></start>
                            <end><![CDATA[</nav>]]></end>
                        </stripBetween>                                             
                    </transformer>
                    
Using the latest version of http collector

**Comment by essiembre** [comment]
By default regex asterisk is "greedy".  Try with ``<nav.*?>`` instead.  I recommend you use an online regular expression tool for testing.  If you suspect the problem is something else, feel free to reopen.

**Comment by butchersoft1** [comment]
Thanks I'll give it a go, but I have tried many different regex catch and none have worked (where in the past they used to).   I reverted to adding a text tags before and after every section I need removed and just going with a flat text extract between <!--ignore-start> and <!--ignore-end>.

I'm trying to remove repeated headers, footer and menu sections.  If you have some advice on best practice the help would be appreciated

**Comment by essiembre** [comment]
You can check here how adding ``?`` matches just what you want to strip here: https://regex101.com/r/94oXsw/2

If you suspect an issue, please re-open with an HTML sample to reproduce.
