### ISSUE TITLE
NullPointerException at com.norconex.commons.lang.VersionUtil.fromJarManifest when trying to extend a Committer

### ISSUE THREAD

**Issue by Dhanvanthri** [Norconex/committer-core#22]
Hello, I'm trying to extend the Norconex Committer system for my application (in Clojure).
I have the following code 
`(def my-committer
  (proxy
      [LogCommitter]
      []
      (doUpsert [upsert-request]
        (println this upsert-request))))`
        
Which is simply creating an instance of the LogCommitter object, with the doUpsert function overloaded to print its input to stdout.
However when I try to start a collector which has my-committer as a Committer instead of LogCommitter, I get  the error specified in the title.
I would appreciate any help with this.

Thanks!

**Comment by Dhanvanthri** [comment]
Here is the complete stacktrace.


  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (13 frames hidden)
```
1. Unhandled java.lang.NullPointerException
   (No message)

          VersionUtil.java:  212  com.norconex.commons.lang.VersionUtil/fromJarManifest
          VersionUtil.java:  179  com.norconex.commons.lang.VersionUtil/doGetDetailedVersion
          VersionUtil.java:  161  com.norconex.commons.lang.VersionUtil/getDetailedVersion
            Collector.java:  482  com.norconex.collector.core.Collector/releaseVersion
            Collector.java:  471  com.norconex.collector.core.Collector/releaseVersions
            Collector.java:  458  com.norconex.collector.core.Collector/getReleaseVersions
            Collector.java:  179  com.norconex.collector.core.Collector/start
NativeMethodAccessorImpl.java:   -2  sun.reflect.NativeMethodAccessorImpl/invoke0
NativeMethodAccessorImpl.java:   62  sun.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  sun.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  498  java.lang.reflect.Method/invoke
            Reflector.java:   93  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:  313  clojure.lang.Reflector/invokeNoArgInstanceMember
                      REPL:   95  norconex-standalone.core/eval9206
                      REPL:   95  norconex-standalone.core/eval9206
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6890  clojure.lang.Compiler/eval
                  core.clj: 3105  clojure.core/eval
                  core.clj: 3101  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  240  clojure.main/repl/read-eval-print/fn
                  main.clj:  240  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  218  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  217  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  750  java.lang.Thread/run

```

**Comment by ohtwadi** [comment]
Hello,

Let's ensure the default HTTP Crawler works in your project first.
The out-of-the-box committer supports printing output to the console. The following `<commiter>` config will do just that.
```XML
<committer class="LogCommitter">
  <logLevel>STDOUT</logLevel>
</committer>
```
Ref: https://opensource.norconex.com/committers/core/v3/apidocs/com/norconex/committer/core3/impl/LogCommitter.html

Also, I am curious about what you are trying to achieve by extending the committer. You may already be aware that we offer committers for a variety of repositories: https://opensource.norconex.com/committers/.

**Comment by Dhanvanthri** [comment]
Yes, the default LogCommitter does work; the code that I pasted is extending the (default) LogCommitter object with a custom doUpsert function.

In fact, all the default committers (LogCommitter, CSVFileCommitter, XMLFileCommitter) seem to work.

Furthermore, my custom committer also works when I compile all the resources and launch it from the command line. However it doesn't work in the clojure repl. 
Maybe the problem can be solved by looking in compiled resources for versions, I am investigating.

I'm trying to extend the committer because I need to import and commit the data using custom logic for my application.

**Comment by ohtwadi** [comment]
The fact that the issue only occurs with in Clojure REPL and not after you run the build tells me that the build generates a required file but your IDE does not. Based on the stack trace, this is the Manifest file. 
When I load up the `commons-lang` project in Eclipse, (probably) maven generates `MANIFEST.MF` file for me under `target\classes\META-INF` and thus everything works fine.

In any case, based on the stack trace, I have added a null check and we will generate a patch in the coming days for you to try.

**Comment by Dhanvanthri** [comment]
Thank you very much; 
I wasn't able to find a MANIFEST.MF file in that directory, so you're definitely onto something.
I'm using Leiningen for project management.

**Comment by Dhanvanthri** [comment]
I just finished testing it with the latest 2.0.2 patch, and I'm still getting the same error

1. Unhandled java.lang.NullPointerException
   (No message)

          VersionUtil.java:  191  com.norconex.commons.lang.VersionUtil/fromUnpackedMavenPomXml
          VersionUtil.java:  180  com.norconex.commons.lang.VersionUtil/doGetDetailedVersion
          VersionUtil.java:  161  com.norconex.commons.lang.VersionUtil/getDetailedVersion
            Collector.java:  482  com.norconex.collector.core.Collector/releaseVersion
            Collector.java:  471  com.norconex.collector.core.Collector/releaseVersions
            Collector.java:  458  com.norconex.collector.core.Collector/getReleaseVersions
            Collector.java:  179  com.norconex.collector.core.Collector/start
NativeMethodAccessorImpl.java:   -2  jdk.internal.reflect.NativeMethodAccessorImpl/invoke0
NativeMethodAccessorImpl.java:   62  jdk.internal.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  jdk.internal.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  566  java.lang.reflect.Method/invoke
            Reflector.java:  167  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:  438  clojure.lang.Reflector/invokeNoArgInstanceMember
                      REPL:   55  norconex-standalone.core/eval7816
                      REPL:   55  norconex-standalone.core/eval7816
             Compiler.java: 7194  clojure.lang.Compiler/eval
             Compiler.java: 7149  clojure.lang.Compiler/eval
                  core.clj: 3215  clojure.core/eval
                  core.clj: 3211  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1990  clojure.core/with-bindings*
                  core.clj: 1990  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  218  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  217  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  829  java.lang.Thread/run

I made sure to get it from sonatype 

(The example link provided on the website needs  to have a "/" after snapshots
     <url>http://oss.sonatype.org/content/repositories/snapshots</url>
-> <url>http://oss.sonatype.org/content/repositories/snapshots/</url>)

Is it possible to have it set some default string in the case that the MANIFEST.MF file is not found? Perhaps there's another way to obtain the version?

**Comment by Dhanvanthri** [comment]
It did actually fix another problem though: When the splash screen is shown 

`05:05:10.085 [sampler-collector] INFO  Collector - 
 _   _  ___  ____   ____ ___  _   _ _______  __
| \ | |/ _ \|  _ \ / ___/ _ \| \ | | ____\ \/ /
|  \| | | | | |_) | |  | | | |  \| |  _|  \  / 
| |\  | |_| |  _ <| |__| |_| | |\  | |___ /  \ 
|_| \_|\___/|_| \_\\____\___/|_| \_|_____/_/\_\

============== C O L L E C T O R ==============

Collector and main components:

Collector:          norconex-standalone 0.1.0-SNAPSHOT
Collector Core:     norconex-standalone 0.1.0-SNAPSHOT
Importer:           norconex-standalone 0.1.0-SNAPSHOT
Lang:               norconex-standalone 0.1.0-SNAPSHOT
Committer(s):
  Core:             norconex-standalone 0.1.0-SNAPSHOT
  LogCommitter$ff19274a: norconex-standalone 0.1.0-SNAPSHOT
Runtime:
  Name:             OpenJDK Runtime Environment
  Version:          11.0.18+10
  Vendor:           Oracle Corporation
`

Till this patch, I was getting "undefined" for all the values for the main componenents, but now I'm getting a version number.
This output is from the terminal when launching the collector (through the main), not from the repl.

**Comment by ohtwadi** [comment]
Well this is strange. 
Line 191 of com.norconex.commons.lang.VersionUtil is looking for pom.xml and can't find it.
https://github.com/Norconex/commons-lang/blob/bugfix/NPE-fromJarManifest/src/main/java/com/norconex/commons/lang/VersionUtil.java#L191

I don't have a Clojure environment to test but it looks like your project structure is not conforming to a typical Maven project.

**Comment by essiembre** [comment]
A new v2 snapshot release was made which should now prevent any exceptions from being thrown when there is a problem establishing the version.  Please confirm.

**Comment by Dhanvanthri** [comment]
I just tested it with the latest snapshot update on sonatype and I'm SUPER pleased to say that my repl is now working as expected; Thank you so much for your patient and quick resolution!
I'm still testing it, but the main functionality is definitely working without any obvious issues!

**Comment by essiembre** [comment]
Glad to hear!

**Comment by Dhanvanthri** [comment]
Also with the latest patch, when I start the collector from the clojure repl I get the following (correct) splash information! 
 ```
_   _  ___  ____   ____ ___  _   _ _______  __
| \ | |/ _ \|  _ \ / ___/ _ \| \ | | ____\ \/ /
|  \| | | | | |_) | |  | | | |  \| |  _|  \  / 
| |\  | |_| |  _ <| |__| |_| | |\  | |___ /  \ 
|_| \_|\___/|_| \_\\____\___/|_| \_|_____/_/\_\

============== C O L L E C T O R ==============

Collector and main components:

Collector:          Norconex HTTP Collector 3.0.1 (Norconex Inc.)
Collector Core:     Norconex Collector Core 2.0.1 (Norconex Inc.)
Importer:           Norconex Importer 3.0.0 (Norconex Inc.)
Lang:               Norconex Commons Lang 2.0.2-SNAPSHOT (Norconex Inc.)
Committer(s):
  Core:             Norconex Committer Core 3.0.0 (Norconex Inc.)
  LogCommitter$ff19274a: undefined
Runtime:
  Name:             OpenJDK Runtime Environment
  Version:          11.0.18+10
  Vendor:           Oracle Corporation

```
